project:
  type: website
  output-dir: docs
  resources:
    - pdfs/**
    
website:
  title: "Kimberly's First Marathon!"
  site-url: "https://kila-kimberly.github.io/1st_marathon/"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - presentations.qmd 
  favicon: "images/face.jpeg"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

